# Generated by Django 3.2.16 on 2023-01-08 07:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0004_remove_contact_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Loan',
        ),
    ]
